### ISSUE TITLE
To Do > Prompt to Enter Text

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#48]
The prompt to enter text should always be there if there is no text. 
ex. if you click to enter text type in a couple words and then backspace all the characters the "Feeling distracted" text should show again. This should also happen if you click into the box to type and click out without entering anything.

![screen shot 2014-12-30 at 12 03 47 pm](https://cloud.githubusercontent.com/assets/7152379/5580667/0c3d093e-901c-11e4-886d-802f2803cb4b.png)

**Comment by GarrethDottin** [comment]
Fixed

**Comment by Ryan-Parker** [comment]
This is still an issue. The text should come back when you click off the input bar 

![screen shot 2015-01-11 at 10 49 00 pm](https://cloud.githubusercontent.com/assets/7152379/5698776/1be5c23c-99e4-11e4-9e56-5972a3220cd5.png)

**Comment by Ryan-Parker** [comment]
We could also handle it like the "To" input here http://www.kayak.com/

It is faded in the background and only goes away once a user types something. But if you backspace back all the way or click off the input field it comes back. This is expected behavior
