### ISSUE TITLE
To Do List > Completed Tasks > Remove # so task will be in line

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#53]
![screen shot 2015-01-02 at 9 19 05 pm](https://cloud.githubusercontent.com/assets/7152379/5601303/1995534c-92c5-11e4-8c6f-a06cd905a725.png)

**Comment by GarrethDottin** [comment]
Fixed issue with spacing

**Comment by Ryan-Parker** [comment]
![screen shot 2015-01-11 at 10 47 01 pm](https://cloud.githubusercontent.com/assets/7152379/5698761/c9029784-99e3-11e4-83bf-b5dbf62d82bf.png)

Still an issue
