### ISSUE TITLE
Completed To Do List > Spacing

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#74]
Sometimes there wont be a space between the end of the Tasks and the start of the Date. 

![screen shot 2015-01-12 at 5 38 39 pm](https://cloud.githubusercontent.com/assets/7152379/5712611/e5c380b0-9a81-11e4-8536-26b690a052cd.png)

**Comment by GarrethDottin** [comment]
some letters take up more space than others the currency character count should fix that

**Comment by Ryan-Parker** [comment]
Still seeing this issue, but might be related to issue #71 

![screen shot 2015-01-14 at 10 12 34 am](https://cloud.githubusercontent.com/assets/7152379/5740931/eb47ba56-9bd5-11e4-8e1c-afd66a95d8de.png)

**Comment by Ryan-Parker** [comment]
Still breaks too 

![screen shot 2015-01-14 at 5 06 30 pm](https://cloud.githubusercontent.com/assets/7152379/5748659/c0585e10-9c0f-11e4-8eae-bbf227af733d.png)
